### ISSUE TITLE
Breadcrumb leads to a blank page

### ISSUE THREAD

**Issue by yarons** [hasadna/OpenTrainCommunity#26]
Reproduction steps:
1. Select source and destination stations.
2. Select from and to dates.
3. Click „הצג מידע”.
4. After the data will appear click on „מתחנת מוצא לתחנת יעד - חודש ושנה” at the top of the page.

The page turns blank at this step and I need to click Back in order to restore the page.

Thanks.

**Comment by nirgilboa** [comment]
Fixed - thank you :-)

https://github.com/hasadna/OpenTrainCommunity/commit/8b53e24cc60b06db48aa05cb73673aa2b8264397
