### ISSUE TITLE
otrain.org currently only uses http, instead of https

### ISSUE THREAD

**Issue by chaimkut** [hasadna/OpenTrainCommunity#36]
In general there's a preference for sites to use HTTPS , though since there's no private user data this is not a pressing matter. Example: https://oknesset.org , https://kikar.org/

https://security.stackexchange.com/questions/142496/which-security-measures-make-sense-for-a-static-web-site

**Comment by uda** [comment]
Will check and configure it

**Comment by nirgilboa** [comment]
Done using Let's Encrypt and certbot :)
