### ISSUE TITLE
hasadna.redashapp.com no longer works

### ISSUE THREAD

**Issue by chaimkut** [hasadna/OpenTrainCommunity#39]
Documentation at
[Accessing the data using redash](https://github.com/hasadna/OpenTrainCommunity/blame/583eefe4be35ad3a0e3343c2ea8315f65d28053d/docs/accessing_the_data_using_redash.rst#L9) (most up to date version of [docs](https://github.com/hasadna/OpenTrainCommunity/blob/master/docs/accessing_the_data_using_redash.rst))

> You can share the results with others.
Pretty cool tool!
http://hasadna.redashapp.com

`hasadna.redashapp.com` doesn't work.

**Comment by uda** [comment]
The redash is now at https://app.redash.io/hasadna/

**Comment by chaimkut** [comment]
Looks like the redash apps requires the user to signup the org (hasadna)'s installation. Unclear from the website how to do this. Only provides a login screen, but doesn't explain how to register if you're not already 'signed up' ...

**Comment by uda** [comment]
I am not the maintainer of the app, so as to how to, simply connect using a Google account, you can later reset your password if you prefer to sign in using user/pass.

I am not sure why, but I can think of a few reasons to put a 3rd party SSO service as a requirement. In any case, you are invited to post about it in the forum https://forum.hasadna.org.il/c/10-category

**Comment by nirgilboa** [comment]
Closing this - we removed redash for the moment
