### ISSUE TITLE
Different background colors

### ISSUE THREAD

**Issue by chaimkut** [hasadna/OpenTrainCommunity#53]
When initially loading the homepage we see a light blue background

![image](https://user-images.githubusercontent.com/1482729/43482902-bac98320-9512-11e8-9adb-74c9a90b0d35.png)

Then when the page loads, it becomes dark blue:

![image](https://user-images.githubusercontent.com/1482729/43482926-ca259aca-9512-11e8-878e-53ce371079ed.png)

Then when the route is being chosen, the background becomes light blue again

![image](https://user-images.githubusercontent.com/1482729/43482971-e6404a66-9512-11e8-8968-7cf271bbda0f.png)

Seems like it should be more consistent...

**Comment by nirgilboa** [comment]
Deprecated in favour of other direction in the UI
