### ISSUE TITLE
Requirements page contains a duplicate entry

### ISSUE THREAD

**Issue by xsxso** [hasadna/OpenTrainCommunity#59]
train2/requirements.txt has duplicate entries of 

`django-cors-headers==2.0.0`

thereby yielding this error

> Double requirement given: django-cors-headers==2.0.0 (from -r requirements.txt (line 16)) (already in django-cors-headers==2.0.0 (from -r requirements.txt (line 10)), name='django-cors-headers')

cannot proceed from here  : (

**Comment by nirgilboa** [comment]
Thanks ! fixed it :)

**Comment by nirgilboa** [comment]
Sorry forgot to check the PR
